### ISSUE TITLE
ABI file is missing from repo

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.contracts#116]
ABI file is missing. should be a problem but right now cut could not generate correct ABI for eosio.token.

Could we put the manually crafted ABI back or fix the ABI generator for eosio.token?

**Comment by dixia** [comment]
invalid ABI:
[eosio.token.abi.txt](https://github.com/EOSIO/eosio.contracts/files/2504309/eosio.token.abi.txt)

**Comment by wanderingbort** [comment]
looks like neither of the tables types are added
