### ISSUE TITLE
REX: table entries not cleared from rexfund after withdrawing, leading to excessive system contract RAM consumption over time

### ISSUE THREAD

**Issue by acoutts** [EOSIO/eosio.contracts#118]
In the current implementation after a user sells all of their REX tokens and withdraws everything from the rex fund, a table entry remains for their account with a 0.0000 balance. Over time this will lead to excessive wasteful RAM usage by the system contract for these zero balance entries.

**Comment by acoutts** [comment]
@zorba80

**Comment by zorba80** [comment]
Users can delete their `rex_balance` and `rex_fund` records and free their RAM using `closerex` action.
