### ISSUE TITLE
Error 3050003: eosio_assert_message assertion failure when cleos system newaccount ...

### ISSUE THREAD

**Issue by danX-4q** [EOSIO/eosio.contracts#137]
eosio: 1.4.3
eosio.cdt: 1.4.1
eosio.contracts: 1.5.0

follow by https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence 
when 《Step 10a: Create a staked account》

> cleos system newaccount eosio --transfer accountnum11 EOS8mUftJXepGzdQ2TaCduNuSPAfXJHf22uex4u41ab1EVv9EAhWt --stake-net "100000.0000 SYS" --stake-cpu "100000.0000 SYS" --buy-ram-kbytes 8192

console get:

> Error

 3050003: eosio_assert_message assertion failure

log get:

> error 2018-11-29T06:31:48.754 thread-0  http_plugin.cpp:580           handle_exception     ] FC Exception encountered while processing chain.push_transaction
> debug 2018-11-29T06:31:48.754 thread-0  http_plugin.cpp:581           handle_exception     ] Exception Details: 3050003 eosio_assert_message_exception: eosio_assert_message assertion failure
> assertion failure with message: system contract must first be initialized
>     {"s":"system contract must first be initialized"}
>     thread-0  wasm_interface.cpp:934 eosio_assert
> pending console output: 
>     {"console":""}
>     thread-0  apply_context.cpp:72 exec_one

but i have deploy eosio.token, and create xxxxx SYS, issue yyyyy SYS to account eosio.

please, how to resolve it.

**Comment by surabhil** [comment]
+1

**Comment by yinogong** [comment]
+1

**Comment by surabhil** [comment]
with the v1.5.1 of system contract, the init action needs to be called first with the core symbol.
Run this
cleos push action eosio '[0,{core synbol}]' -p eosio
And then try to create new accounts

**Comment by FortisFortuna** [comment]
Thanks @k26dr and @surabhil 

This is what I used:
`cleos push action eosio init '[0, "4,EOS"]' -p eosio@active`

**Comment by fuatkarakus** [comment]
I have same issue, nodeos v1.8.7, 

> system newaccount eosio --transfer kyc1 <PUBLIC_KEY> 
    --stake-net "100000000.0000 SYS" --stake-cpu "100000000.0000 SYS" --buy-ram-kbytes 1024000
   Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: overdrawn balance
pending console output:

When i use this:

> cleos push action eosio init '[0, "4,EOS"]' -p eosio@active
Error 3050003: eosio_assert_message assertion failure
Error Details:
assertion failure with message: system contract has already been initialized
pending console output:

Is there any solution ?

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
