### ISSUE TITLE
testing addressbook example , it does not work.

### ISSUE THREAD

**Issue by snipper15** [EOSIO/eosio.contracts#152]
code from : https://developers.eos.io/eosio-home/docs/data-persistence.
1.Compile the Contract . ok
2.Deploy the Contract : ok
3.Test the Contract : 
  3.1 cleos push action addressbook upsert '["alice", "alice", "liddell", "123 drink me way", "wonderland", "amsterdam"]' -p alice@active

show error :
   cleos -u http://url push action addressbook upsert '["alice", "alice", "liddell", "123 drink me way", "wonderland", "amsterdam"]' -p alice@active
Error 3090003: Provided keys, permissions, and delays do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"alice","permission":"active"}', but does not have signatures for it.

but now , my wallet is unlocked and the private key has imported into my wallet.

cleos -u http://url get accounts owner.key
{
  "account_names": [
    "addressbook"
  ]
}

cleos version clientBuild version: ea08cfd3

I don't know why , thank you!

**Comment by mudguts70** [comment]
I got the exact same error message, any updates?
