### ISSUE TITLE
Bancor formula in exchange_state

### ISSUE THREAD

**Issue by kaynarov** [EOSIO/eosio.contracts#157]
let:
C0 -- reserve before buying / after selling;
C1 -- reserve after buying / before selling;
T = C1 - C0;
R0 -- supply before buying / after selling;
R1 -- supply after buying / before selling;
E = R1 - R0;
w -- connector weight;
F = 1/w.

according to [bancor formula](https://drive.google.com/file/d/0B3HPNP-GDn7aRkVaV3dkVl9NS2M/view): T = C0 * ((1 + E/R0)^F - 1);
we have R1, C1, F and E, so:
T = (C1 - T) * ((1 + E/(R1 - E))^F - 1)
T = C1 * A / (1 + A), where A = ((1 + E/(R1 - E))^F - 1)
or we can just use [this](https://github.com/bancorprotocol/contracts/blob/973c9919e146a1b61297632f3253ee1c891462a9/solidity/contracts/converter/BancorFormula.sol#L206)
but [here](https://github.com/EOSIO/eosio.contracts/blob/3a63dae5e6ae3fda6c9a4ec97f17315638b7832e/eosio.system/src/exchange_state.cpp#L37): T = C1 * A
did I miss something?

**Comment by zorba80** [comment]
Addressed in PR #222.
