### ISSUE TITLE
New type of multisig system contract

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eosio.contracts#177]
Just aware that new data type checksum256$ has been introduced in the approve action of system multisig contract,if i wanna approve a proposal via http api,what would be the data format like? hex string? And also aware that the proposal_hash param could be null,what should the data format look like if wanna keep this param null

**Comment by arhag** [comment]
If you want to keep it null, just don't include the `proposal_hash` field in the JSON of the action data. If you want to use the new field, include the `proposal_hash` field in the JSON object with a string value equal to the hex representation of the transaction ID of the proposed transaction. The latest `cleos multisig review` will show the transaction ID in the results.

**Comment by huanglei579** [comment]
Have you solved this problem that  new data type checksum256$ has been introduced in the approve action of system multisig contract? @crazybits
