### ISSUE TITLE
Unable to compile with packaged eosio and eosio.cdt

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.contracts#180]
Ubuntu 18.04, `eosio_1.6.0-1-ubuntu-18.04_amd64.deb`, `eosio.cdt_1.5.0-1_amd64.deb`.

The build script produces an error as below. A workaround is to comment out `include(UnitTestsExternalProject.txt)` in `CMakeLists.txt`.

The reason is, that binary packages do not include EOSIO CMake macros.

```
	=========== Building eosio.contracts ===========

-- Setting up Eosio Wasm Toolchain 1.5.0 at /usr
-- Using eosio.cdt version 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/eosio/build/eosio.contracts/build
[ 15%] Built target eosio.bios.wasm
[ 15%] Performing configure step for 'contracts_unit_tests'
CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "Findeosio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "eosio", but
  CMake did not find one.

  Could not find a package configuration file provided by "eosio" with any of
  the following names:

    eosioConfig.cmake
    eosio-config.cmake

  Add the installation prefix of "eosio" to CMAKE_PREFIX_PATH or set
  "eosio_DIR" to a directory containing one of the above files.  If "eosio"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Error at CMakeLists.txt:11 (EOSIO_CHECK_VERSION):
  Unknown CMake command "EOSIO_CHECK_VERSION".


[ 26%] Built target eosio.msig.wasm
-- Configuring incomplete, errors occurred!
See also "/home/eosio/build/eosio.contracts/build/tests/CMakeFiles/CMakeOutput.log".
CMakeFiles/contracts_unit_tests.dir/build.make:106: recipe for target 'contracts_unit_tests-prefix/src/contracts_unit_tests-stamp/contracts_unit_tests-configure' failed
make[2]: *** [contracts_unit_tests-prefix/src/contracts_unit_tests-stamp/contracts_unit_tests-configure] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/contracts_unit_tests.dir/all' failed
make[1]: *** [CMakeFiles/contracts_unit_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target eosio.wrap.wasm
[ 31%] Building CXX object eosio.wrap/CMakeFiles/eosio.wrap.wasm.dir/src/eosio.wrap.cpp.o
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <exec> does not have a ricardian contract
Warning, action <exec> does not have a ricardian contract
[ 36%] Linking CXX executable eosio.wrap.wasm
[ 36%] Built target eosio.wrap.wasm
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by projectoblio** [comment]
Please fucking

**Comment by ramtej** [comment]
Same issue here. Btw. what happens with the debian builds that we contributed many months ago? Some people prefer to use solid/secure linux distros on the servers and not the latest & greatest stuff.

**Comment by projectoblio** [comment]
idk what happened, just installed a missing lib and restarted and it worked. error was slightly different than the issue here

**Comment by Azure-kyLIN** [comment]
The same problem here; 
OS: MACOS Mojave 10.14.3

Struggling built eosio and eosio.cdt while still cannot done with the contracts.
error message deal with "EOSIO_CHECK_VERSION".

> CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "Findeosio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "eosio", but
  CMake did not find one.
Could not find a package configuration file provided by "eosio" with any of
  the following names:
eosioConfig.cmake
eosio-config.cmake
Add the installation prefix of "eosio" to CMAKE_PREFIX_PATH or set
  "eosio_DIR" to a directory containing one of the above files.  If "eosio"
  provides a separate development package or SDK, be sure it has been
  installed.
CMake Error at CMakeLists.txt:11 (EOSIO_CHECK_VERSION):
  Unknown CMake command "EOSIO_CHECK_VERSION".


Why no guys help with this issue? At least tell us how to compile them by our own.

**Comment by danazkari** [comment]
This issue has been here for a while now :) I'm getting this exact same error and I'm running it on a docker image with Ubuntu 18.04:

```Dockerfile
FROM ubuntu:18.04

ENV WORK_DIR /opt/application
ENV EOSIO_PACKAGE_URL https://github.com/EOSIO/eos/releases/download/v1.7.4/eosio_1.7.4-1-ubuntu-18.04_amd64.deb
ENV EOSIO_CDT_URL https://github.com/EOSIO/eosio.cdt/releases/download/v1.5.0/eosio.cdt_1.5.0-1_amd64.deb 

RUN apt-get update && apt-get install -y wget build-essential cmake \
  && wget -O /eosio.deb $EOSIO_PACKAGE_URL \
  && wget -O /eosio.cdt.deb $EOSIO_CDT_URL \
  && apt-get install -y /eosio.deb \
  && apt-get install -y /eosio.cdt.deb \
  && apt-get install -y --no-install-recommends jq curl git \
  && rm /eosio.deb /eosio.cdt.deb \
  && apt-get remove -y wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# Define working directory
WORKDIR $WORK_DIR
# Copy application code
COPY ./ $WORK_DIR
```
I build that one and launch it, I go to `opt` and execute:
```bash
$ git clone --branch v1.6.1 https://github.com/EOSIO/eosio.contracts.git /opt/eosio.contracts
$ cd /opt/eosio.contracts/
$ ./build.sh
```
Which yields the same error described here. How what am I missing? The docs do not explain a lot and up to a few weeks ago, we used to just use the `eosio/eos-dev` docker image, which has been deleted, along with it's source code. It's a shame, that used to work beautifully to compile these contracts.

If a fix for this isn't possible to provide in the near future, can we please get at least a copy of the source code of that docker image? That would greatly help to at least have a way to consistently build these contracts.

**Comment by danazkari** [comment]
So I just figured out (through the use of `grep` and `find`) that the error was originating on `tests` directory, I ignored the error and deployed the contracts, and everything seemed to work (ran into some CPU issues but that's on my side I guess...) so yeah... just... ignore it and carry on!

**Comment by xqyww123** [comment]
Comment line 77 ~ 86 in version 1.7.0
```
#ExternalProject_Add(
#    contracts_unit_tests
#  LIST_SEPARATOR | # Use the alternate list separator
#  CMAKE_ARGS -DCMAKE_BUILD_TYPE=${TEST_BUILD_TYPE} -DCMAKE_FRAMEWORK_PATH=${TEST_FRAMEWORK_PATH} -DCMAKE_MODULE_PATH=${TEST_MODULE_PATH} -DEOSIO_ROOT=${EOSIO_ROOT} -DLLVM_DIR=${LLVM_DIR}
#  SOURCE_DIR ${CMAKE_SOURCE_DIR}/tests
#  BINARY_DIR ${CMAKE_BINARY_DIR}/tests
#  BUILD_ALWAYS 1
#  TEST_COMMAND   ""
#  INSTALL_COMMAND ""
#)
```

**Comment by loveship00** [comment]
eos, shit
