### ISSUE TITLE
Producer_pay.cpp doesn't use perblock_rate & standby_rate values 

### ISSUE THREAD

**Issue by basarrcan** [EOSIO/eosio.contracts#190]
I am trying to change inflation and reward values and noticed that claimrewards function doesn't use those variables, instead makes a hardcoded distribution.

```
const double   continuous_rate       = 0.04879;          // 5% annual rate
const double   perblock_rate         = 0.0025;           // 0.25%
const double   standby_rate          = 0.0075;           // 0.75%
const uint32_t blocks_per_year       = 52*7*24*2*3600;   // half seconds per year
```

are the const vars that supposed to be used on reward calculation.

```
auto to_producers       = new_tokens / 5;
auto to_savings         = new_tokens - to_producers;
auto to_per_block_pay   = to_producers / 4;
auto to_per_vote_pay    = to_producers - to_per_block_pay;
```

is the calculation of perblock and standby rates.

**Comment by zorba80** [comment]
Variables `perblock_rate` and `standby_rate` were left from older versions of the code by mistake. I will delete them. I prefer the current definitions, i.e., `to_producers` is fraction of `new_tokens` which represents the tokens issued by inflation. The rest goes to savings. Similarly `to_per_block_pay` is a fraction of `to_producers`. These calculations have two advantages: 1) Any rounding errors in `to_per_block_pay = to_producers / 4` are absorbed by `to_per_vote_pay = to_producers - to_per_block_pay`. 2) Variables are calculated relative to one another as opposed to begin functions of `perblock_rate` and `standby_rate` which in theory can vary independently. However, we should move the definition of the ratios (4 and 5) to outside the equations.

**Comment by zorba80** [comment]
Issue has been addressed.
