### ISSUE TITLE
Proposal: Add blacklist in the system contract

### ISSUE THREAD

**Issue by noprom** [EOSIO/eosio.contracts#192]
Currently, the blacklist is manually added in the config.ini file, which is very detrimental to the update. With changes in BP, transactions will be allowed to pass to those who do not add the blacklist. This is not favorable.
It is recommended that this blacklist be added to the system contract.

@heifner @bytemaster

**Comment by deckb** [comment]
We are doing some clean up and are closing old issues. Please reopen in the [new system repo](https://github.com/EOSIO/eosio.system).
