### ISSUE TITLE
Use a new metric for producer per-vote pay

### ISSUE THREAD

**Issue by zorba80** [EOSIO/eosio.contracts#20]
A new metric is used for producer per-vote pay. The metric combines vote weight and the time duration a producer has held the vote.

A producer's share (call it `vs`) of the per-vote bucket is calculated as follows:

- vs is is initially set to zero.
- At time `vt1` a voter votes for the producer with weight `w1`. `vs` stays zero.
- Later, at time `vt2` a second voter votes for the producer with weight `w2`. At this point, `vs` is updated to `vs = w1 * (vt2 - vt1)`.
- At later time, `vt3`, a third voter votes for the producer. Update `vs` to `vs = w1 * (vt2 - vt1) + (w1 + w2) * (vt3 - vt2)`.
- When the producer `claimrewards` at time `ct`, update `vs` to `vs = w1 * (vt2 - vt1) + (w1 + w2) * (vt3 - vt2) + (w1 + w2 + w3) * (ct - vt3)`.
- Producer's per-vote pay is then calculated as `(vs * per-vote-bucket) / (total vs of all producers)`.
- After a producer `claimrewards`, his share `vs` is set to zero. 
 
A producer who carries some votes, can have his vote-pay share increase with time if he doesn't `claimrewards`. In a sense vote-pay share can increase due to inactivity. To avoid that, we don't update vote-pay share of producers who haven't `claimrewards` in the past 3 days when a voter votes or updates his stake.

**Comment by arhag** [comment]
Replaced by #58.

**Comment by arhag** [comment]
Resolved by #58.
