### ISSUE TITLE
Proposal: token information table

### ISSUE THREAD

**Issue by ekkis** [EOSIO/eosio.contracts#200]
At present there is no authoritative way to discover key information about the tokens that a smart contract (including this one) may handle

I propose that there should be an authoritative way for discovery of this information by creating a table in the contract as follows:
```
struct [[eosio::table]] info_struct {
	string symbol;
	int decimals = 8;
	int supply;
	string issuerName;
	string issuerUri;
	string description;
	uint32_t createdOn;
};
eosio::multi_index<name("info"), info_struct> info;
```
where the contract could maintain one row per token it manages.  this information could then be collated into registries that could be used by applications to properly use the tokens, where the contract owner need only notify the registry of the existence of the contract and the registry picks up all relevant info

please note that `supply` would be used for the initial issuance for fixed-supply tokens but could be maintained by the contract in case of mint-and-burn tokens

also note that as opposed to the current `stat` table which segregates information by scope, the info table should offer all its info under a single, canonical scope.  this is to avoid the impasse at present where in order to retrieve information about EOS, I have to know the symbol and there is no catalogue of the existing symbols

**Comment by DenisCarriere** [comment]
This information doesn't need to be stored at the base protocol level.

There's already offchain solutions that extends the metadata of tokens

**Comment by ekkis** [comment]
maybe, but none of them are authoritative

**Comment by deckb** [comment]
We are doing some housekeeping. If desired please reopen in the [new token contract repo](https://github.com/eosio/eosio.token).

**Comment by ekkis** [comment]
it's fine to close it.  I no longer care.  I've abandoned the EOS ecosystem
