### ISSUE TITLE
Reset the vote decay of any account by delegating to them

### ISSUE THREAD

**Issue by n8d** [EOSIO/eosio.contracts#216]
It's possible to reset the vote decay of any account by delegating any amount of the system token to them, such as 0.0001 EOS. This was seen on EOS mainnet on a bunch of large accounts today:

https://bloks.io/account/getstuffdone

This probably shouldn't be possible, as it undermines the decay system.

Update: This only works when doing a delegate + transfer (as in using `--transfer` with cleos).

**Comment by jafri** [comment]
Reference action that will reset decay:

```
{
            account: 'eosio',
            name: 'delegatebw',
            authorization: [{
              actor: 'staker',
              permission: 'active'
            }],
            data: {
              from: 'staker',
              receiver: 'voter',
              stake_net_quantity: '0.0001 EOS',
              stake_cpu_quantity: '0.0000 EOS',
              transfer: true
            }
}
```

**Comment by deckb** [comment]
With the introduction of Stake based rewards in https://github.com/EOSIO/eosio.system 2.0.0-rc1 I believe this issue is no longer relevant. Please reopen in the new repo if you believe this is in error.
