### ISSUE TITLE
eosio.contracts v1.6.0 build error (eos v1.7.1, eosio.cdt v1.5.0)

### ISSUE THREAD

**Issue by evsward** [EOSIO/eosio.contracts#221]
```
        =========== Building eosio.contracts ===========

-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting up Eosio Wasm Toolchain 1.5.0 at /usr/local/eosio.cdt
-- Building eosio.contracts v1.6.0
-- Using eosio.cdt version 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /root/work/eosio.contracts/build
```
...
```
-- Using eosio version 1.7.1
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/root/work/eosio.contracts/tests/Boost_INCLUDE_DIR
   used as include directory in directory /root/work/eosio.contracts/tests
libir
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests
liblogging
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests
libplatform
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests
libruntime
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests
libwasm
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests
libwast
    linked by target "unit_test" in directory /root/work/eosio.contracts/tests

-- Configuring incomplete, errors occurred!
```

**Comment by evsward** [comment]
**These libs can't be found in my env. I tried to find them in "/home/xxx/opt/eosio/" and "/home/xxx/opt/boost/", are there any other positions including these libs?:**
- libir
- liblogging
- libplatform
- libruntime
- libwasm
- libwast

**Comment by evsward** [comment]
**While the build failed to achieve the final success, the contracts in the build directory were compiled in bulk and ready to use.**

> eosio.contracts/build/contracts/*

**Comment by bankerbet** [comment]
also build failed on Mac,
already brew install eosio and eosio.cdt

$./build.sh 
	=========== Building eosio.contracts ===========

-- Setting up Eosio Wasm Toolchain 1.5.0 at //usr/local
-- Building eosio.contracts v1.6.0
-- Using eosio.cdt version 1.5.0
-- Configuring done
-- Generating done
-- Build files have been written to: /develop/github/eosio.contracts/build
[ 11%] Performing configure step for 'contracts_unit_tests'
[ 11%] Performing build step for 'contracts_project'
CMake Warning at CMakeLists.txt:7 (find_package):
  By not providing "Findeosio.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "eosio", but
  CMake did not find one.

  Could not find a package configuration file provided by "eosio" with any of
  the following names:

    eosioConfig.cmake
    eosio-config.cmake

  Add the installation prefix of "eosio" to CMAKE_PREFIX_PATH or set
  "eosio_DIR" to a directory containing one of the above files.  If "eosio"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Error at CMakeLists.txt:11 (EOSIO_CHECK_VERSION):
  Unknown CMake command "EOSIO_CHECK_VERSION".


-- Configuring incomplete, errors occurred!
See also "/develop/github/eosio.contracts/build/tests/CMakeFiles/CMakeOutput.log".
[ 16%] Built target eosio.bios
[ 33%] Built target eosio.msig
make[2]: *** [contracts_unit_tests-prefix/src/contracts_unit_tests-stamp/contracts_unit_tests-configure] Error 1
make[1]: *** [CMakeFiles/contracts_unit_tests.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Built target rex.results
[100%] Built target eosio.wrap
[100%] Built target eosio.token
[100%] Built target eosio.system
[ 16%] No install step for 'contracts_project'
[ 22%] No test step for 'contracts_project'
[ 27%] Completed 'contracts_project'
[ 55%] Built target contracts_project
make: *** [all] Error 2

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
