### ISSUE TITLE
Only eosio account authorized to create new accounts.

### ISSUE THREAD

**Issue by MerouaneBen** [EOSIO/eosio.contracts#224]
hi, is there a way to protect the creation of accounts in eos. what I want is to only authorize  eosio account to create new accounts. thanks  for the help

**Comment by smlu** [comment]
If you're planning to make a new chain based on eos you can modify system contract so that it requires authorization from`eosio` when creating new account. To do this, you can simply put code line `require_auth(_self)` [here](https://github.com/EOSIO/eosio.contracts/blob/8c03c9132b1bf8244d6c4724f2dede4bda352e68/contracts/eosio.system/src/eosio.system.cpp#L385). This will make sure `eosio` is present when creating new account. Afterwards you can also remove unused [if statement](https://github.com/EOSIO/eosio.contracts/blob/8c03c9132b1bf8244d6c4724f2dede4bda352e68/contracts/eosio.system/src/eosio.system.cpp#L386-L407).

**Comment by MerouaneBen** [comment]
thanks for your  reply @smlu , I'm planing to  start a sister chain, but I don't need the `eosio.system` contract (I don't need all the voting and stacking actions...), I don't know if I can implement this in `eosio.bios` contract instead.

**Comment by smlu** [comment]
I'd suggest you first start with current `eosio.system` contract and then gradually modify and remove parts you don't want. There are some functionalists that if removed or modified incorrectly will cause the chain to not work properly. Some of those are [scheduling producer](https://github.com/EOSIO/eosio.contracts/blob/master/contracts/eosio.system/src/voting.cpp#L88), [ram](https://github.com/EOSIO/eosio.contracts/blob/master/contracts/eosio.system/src/delegate_bandwidth.cpp#L107) and [bandwidth](https://github.com/EOSIO/eosio.contracts/blob/master/contracts/eosio.system/src/delegate_bandwidth.cpp#L240) resources etc... 
Keep in mind there are also [native actions](https://github.com/EOSIO/eos/blob/14a65aca147edf51fd86a958949e237fd430b9ed/libraries/chain/controller.cpp#L193-L206) embedded in eos node which you'd probably want to modify too.

**Comment by MerouaneBen** [comment]
Thanks @smlu for the clarifications !

**Comment by iamveritas** [comment]
> thanks for your reply @smlu , I'm planing to start a sister chain, but I don't need the `eosio.system` contract (I don't need all the voting and stacking actions...), I don't know if I can implement this in `eosio.bios` contract instead.

try to add your implementation on eosio.bios here:
https://github.com/EOSIO/eosio.contracts/blob/8c03c9132b1bf8244d6c4724f2dede4bda352e68/contracts/eosio.bios/include/eosio.bios/eosio.bios.hpp#L69

**Comment by MerouaneBen** [comment]
I've tried to add the `require_auth(_self);` to `eosio.bios.hpp` but  it didn't work.

**Comment by iamveritas** [comment]
> I've tried to add the `require_auth(_self);` to `eosio.bios.hpp` but it didn't work.

this might sound like a silly question, but did you deployed the eosio.bios?

**Comment by MerouaneBen** [comment]
> > I've tried to add the `require_auth(_self);` to `eosio.bios.hpp` but it didn't work.
> 
> this might sound like a silly question, but did you deployed the eosio.bios?

yeah, I have built the new eosio.bios  contract after the modification, and then I have deployed it to on the blockchain  using `cleos set contract eosio path/to/wasm&abi/dir/of/eosio.bios` .

**Comment by iamveritas** [comment]
it didn't work, any errors? 

if you run
cleos get abi eosio
do you get the eosio.bios abi?
