### ISSUE TITLE
how to write a multiple asynchronous signature program use eosjs since eosio.msig has been updated?

### ISSUE THREAD

**Issue by yplusone** [EOSIO/eosio.contracts#233]
![image](https://user-images.githubusercontent.com/47499743/56458066-91081580-63b4-11e9-84d8-4bcae5ce7f25.png)
I can't figure out what the new argument required, and how can it been given by eosjs?
`                                    await Scattereos.transaction({
                actions: [
                    {
                    account:"eosio.msig",
                    name:"approve",
                      authorization: [{
                        actor: this.$store.state.account.name,
                        permission: this.$store.state.account.authority
                      }
                      ],
                                    data:{
                                    proposer:"yangjiani233",
                                    proposal_name:"kongtou",
                                    level:{
                                        actor:account.name,
                                        permission:account.authority,
                                    },                                   
                                    }
                    }]    
                 
                          }).catch(error => {
                              console.error(error);
                          });   
      }`
It was going well on the old eosio.msig, but on the updated eosio.msig, it is missing one argument
![image](https://user-images.githubusercontent.com/47499743/56458131-5eaae800-63b5-11e9-84e2-f95083a1ccd1.png)

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
