### ISSUE TITLE
Double-move bug in class `system_contract::registration`

### ISSUE THREAD

**Issue by moskvanaft** [EOSIO/eosio.contracts#248]
This code in `eosio.system.hpp`
```
                  template <typename... Args>
                  static constexpr void call( system_contract* this_contract, Args&&... args )
                  {
                     std::invoke( P, this_contract, std::forward<Args>(args)... );
                     for_each<Ps...>::call( this_contract, std::forward<Args>(args)... );
                  }
```
can move values from objects passed by rvalue-reference to parameters to `std::invoke`. Then in next line `call` will use "empty" variables (values already moved from them).
The bug will manifest itself if there are rvalue-reference to classes that have move operator actually moving data instead of copying in parameters.

Possible fix:
```
                     std::invoke( P, this_contract, args... );
                     for_each<Ps...>::call( this_contract, std::forward<Args>(args)... );
```

This bug doesn't affect any current behavior since `registration` used only once with one template parameter. Using it with 2 or more parameters will cause incorrect behavior.

**Comment by arhag** [comment]
Resolved by #272 (and #273 and #274).
