### ISSUE TITLE
Ricardian Examples Missing Required spec_version Metadata Field

### ISSUE THREAD

**Issue by brandonfancher** [EOSIO/eosio.contracts#250]
The latest Ricardian specification version 0.1.1 adds a fourth required field to the metadata: `spec_version`.

Contract Ricardians [here](https://github.com/EOSIO/eosio.contracts/blob/develop/contracts/eosio.token/ricardian/eosio.token.contracts.md) are missing that field.

**Comment by arhag** [comment]
Resolved by #262 (and #263 and #264).
