### ISSUE TITLE
Linker Error: Undefined Reference to secp256k1_rangeproof_info

### ISSUE THREAD

**Issue by sshravan** [EOSIO/eosio.contracts#286]
I run into issues while building the repo. The link stage fails with errors similar to ”undefined reference to secp256k1_rangeproof_info".

I have [eos v1.8.1](https://github.com/EOSIO/eos), [eosio.cdt v1.6.1,](https://github.com/EOSIO/eosio.cdt) and Boost 1.67 installed in Ubuntu 18.04. And libsecp256k1 is also installed. 

Thanks in advance!

**Comment by sshravan** [comment]
https://pastebin.com/iyeZ4CCK

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
