### ISSUE TITLE
eosio.system got fatal error!

### ISSUE THREAD

**Issue by dawnFromDark** [EOSIO/eosio.contracts#287]
the master branch got a fatal error ,it can not be deployed on chain ,the error message is following:

root@ubuntu:/home/time/eosio.contracts/build/contracts# cleos set contract eosio eosio.system/
Reading WASM from /home/time/eosio.contracts/build/contracts/eosio.system/eosio.system.wasm...
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.is_feature_activated unresolveable

my nodeos  version is 1.8.1 and eosio.cdt is 1.6.1, may you tell me what happend about this contract?

**Comment by dawnFromDark** [comment]
the contract which got is eosio.system, may you fix it?

**Comment by dawnFromDark** [comment]
do you have any body to solve this issue ?

**Comment by lsf1001** [comment]
I also met this problem. How did you solve it  ，eosio v1.8.1 eosio.contracts v1.7.0-rc1

**Comment by lsf1001** [comment]
@dawnFromDark

**Comment by MrToph** [comment]
@lsf1001 Running the step described [here in the Preactivate feature
 section](https://github.com/EOSIO/eos/issues/7180) solved the issue for me.
