### ISSUE TITLE
Wrong error message: "unable to find key"

### ISSUE THREAD

**Issue by IhorPeresunko** [EOSIO/eosio.contracts#289]
**Version of EOSJS**  ^20.0.0

**Describe the bug**
An unclear error message that doesn't help to find a problem.

**To Reproduce**
Try to call action *transfer* on 'eosio.token' account with tokens that don't exist on the blockchain.

`   api.transact({
        actions: [{
          account: 'eosio.token',
          name: 'transfer',
          authorization: [{
            actor,
            permission,
          }],
          data: {
            from: account1,
            to: account2,
            quantity: '10 EOA'
          },
        }]
      })`

 (in this example 'EOA' is random symbols).

**Expected behavior**
A clear and concise error description. Like: 'Token doesn't exist on the blockchain'.

**Actual behavior**
Error message: 'assertion failure with message: unable to find key'. Which is not helpful at all. 

Thank you.

**Comment by rommzestz** [comment]
unable to find key    is more correct for this error.  find token as key.

**Comment by deckb** [comment]
We are doing some cleanup and moving to use the https://github.com/EOSIO/eosio.token repo for eosio.token issues. Please reopen there if needed.
