### ISSUE TITLE
build.sh needs more interaction or explanation 

### ISSUE THREAD

**Issue by bkawk** [EOSIO/eosio.contracts#293]
This is a constant stumbling block when following the [BIOS Boot Sequence guide](https://developers.eos.io/eosio-nodeos/docs/bios-boot-sequence) please either update the guide to explain how to find and set the paths and how to pull a specific tag or make the [shell script](https://github.com/EOSIO/eosio.contracts/blob/master/build.sh) more interactive and ask the user for the tag and path they want

**Comment by kedpak** [comment]
I agree, also for some reason there are problems with the build.sh file finding my eosio directory when my eosio installed through Homebrew. Interestingly, version 1.5 works okay. but not the newest.

**Comment by iamveritas** [comment]
bios boot tutorial and script python have been updated to accommodate the changes in 2.0.x
see here: https://github.com/EOSIO/eos/pull/8328

**Comment by iamveritas** [comment]
with the updates to the bios boot tutorial and the [readme.md](https://github.com/EOSIO/eos/blob/master/tutorials/bios-boot-tutorial/README.md) file this should be clearer now.
