### ISSUE TITLE
when delegatebw 5000000000 Error 3100001 occurred

### ISSUE THREAD

**Issue by jmzhuzhonghua** [EOSIO/eosio.contracts#297]
[root@server3 hh]# /disk/gpsio/clgps -u http://localhost:8020 push action gpsio delegatebw '{"from":"'gps1'", "receiver":"'gps1'", "stake_net_quantity":"5000000000.0000 CPS", "stake_cpu_quantity":"5000000000.0000 CPS", "transfer": false}' -p gps1
Error 3100001: Internal state is no longer consistent
Error Details:
Casting a higher bit integer value 0xe6feff7f8bd28c20eb01000000000000 to a lower bit integer value which cannot contain the value, valid range is [0x00000000000000000000000000000000, 0xffffffffffffff7f0000000000000000]

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
