### ISSUE TITLE
50% CW(Bancor connector weight) of RAM market is better than 0.05%

### ISSUE THREAD

**Issue by bezalel** [EOSIO/eosio.contracts#3]
Price-move of EOS/RAM seems same for CW 50% and CW 0.05%.
( https://github.com/EOSIO/eosio.contracts/pull/2 , I think CW changes directly have effect on the amount of additionally-issued RAMCORE tokens which is immediately converted(issued/redeemed) between EOS and RAM, not affecting EOS/RAM price changes. )
But if we use CW 50%, we can optimize token conversion operations.

For CW 0.5%, std:pow(xxx, 0.005) and std:pow(xxx, 200) should be calculated,
but for CW 50%, std:pow(xxx, 0.5) and std:pow(xxx, 2) can be optimized to "sqrt()" and "floating point
multiplication" which is way more efficient.
We can modify Bancor token calculation code in eosio.system using more efficient sqrt() and floating point multi. if CW is set to 50% rather than 0.05%

When EOS Smart Contract code is compiled to WebAssembly code(WASM), floating point operations are automatically converted to use 'Soft Float' library to avoid hardware floating point operations which can cause consensus failure among the different machine. So, I think using std:pow is very expensive. Though sqrt() is also involved with many floating point operations, sqrt() is more efficient than pow(xxx,0.5)

I think CW 50% is better option regarding performance optimization.

**Comment by taokayan** [comment]
Is there any other benefits other than just performance?

**Comment by lychees** [comment]
Compare with the original implementation.
It seems that this issue has been already solved.

https://github.com/EOSIO/eosio.contracts/blob/master/eosio.system/src/exchange_state.cpp#L26
https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/exchange_state.cpp#L27
