### ISSUE TITLE
inconsistent wasm hash of  v1.7.0 using eosio v1.8.3 and eosio.cdt v1.6.2

### ISSUE THREAD

**Issue by JohnnyZhao** [EOSIO/eosio.contracts#342]
trying to build eosio.contracts v1.7.0 using eosio v1.8.3 and eosio.cdt v1.6.2, constantly getting two different wasm hash of eosio.system contract. 

The wasm file size is the same, but with a different hash:
<img width="1440" alt="Screenshot 2019-09-24 at 5 26 46 PM" src="https://user-images.githubusercontent.com/1433855/65495663-16f33400-def2-11e9-9e03-a39604a939eb.png">

I found some slight differences of the two building process, as shown below:

<img width="1440" alt="Screenshot 2019-09-24 at 5 11 38 PM" src="https://user-images.githubusercontent.com/1433855/65495559-e7dcc280-def1-11e9-9832-010b13315321.png">

Here is the hex diff of two different wasm file:

<img width="1440" alt="Screenshot 2019-09-24 at 6 04 00 PM" src="https://user-images.githubusercontent.com/1433855/65498074-37bd8880-def6-11e9-8382-b256b415eb10.png">

```
Platform: Ubuntu 18.04

➜ nodeos --version
v1.8.3
➜ eosio-cpp --version
eosio-cpp version 1.6.2
```

**Comment by JohnnyZhao** [comment]
tried new released v1.8.4, still got two different hashes time to time

**Comment by johndebord** [comment]
@JohnnyZhao @UMU618 According to @larryk85's experimentation thus far, it appears that `make` may be running at different optimization levels depending on an external factor; thus rearranging the code ever so slightly, but yet at the same time keeping the contract's behavior and size the same.

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
