### ISSUE TITLE
Add function to eosio.token contract to add token to account with 0 balance

### ISSUE THREAD

**Issue by znebby** [EOSIO/eosio.contracts#35]
It would be useful to add an "open" function to the eosio.token contract. This would allow a user to add a token to their account with 0 balance. This is useful for "airgrabs"

Something similar to the "signup" function from here https://github.com/generEOS/poorman.token/blob/master/poorman.token.cpp

**Comment by arhag** [comment]
Resolved by #63. Already included in eosio.contracts release [v1.3.0](https://github.com/EOSIO/eosio.contracts/releases/tag/v1.3.0).

**Comment by znebby** [comment]
Thanks for adding the open function. However, shouldn't we first check that the symbol being added exists in the stats table (similar to the issue function).

With the current code, a user can add an unlimited amount of junk (tokens that don't exist) in their RAM.

We need something like:

    auto sym_name = symbol.name();
    stats statstable( _self, sym_name );
    auto existing = statstable.find( sym_name );
    eosio_assert( existing != statstable.end(), "token with symbol does not exist" );
