### ISSUE TITLE
multisig exec executes the proposed transaction but does not transfer the funds

### ISSUE THREAD

**Issue by cuvialabs** [EOSIO/eosio.contracts#364]
I have a multisig transaction that transfers funds from a msig account "mymultisig1a" to "partner1111a" and it seems to execute properly and generates a transaction id but does not actually transfer the funds.

--update--
The cause of the problem was that the transfer amount needs to be 4 decimals instead of 2.,  2.00 should have been 2.0000.    But this exposes a pretty serious problem of creating a transaction ID and reporting a multi-sig transaction as complete when it in fact it failed.   Imagine the problems this would cause in a production financial environment.    It should not be possible to report a multisig transaction as complete when in fact it failed.   
____________

this is all on the jungle test net

PRE TRANS BALANCES

------ SOURCE MSIG ACCOUNT ---------

cleos -u https://jungle2.cryptolions.io get account mymultisig1a created: 2019-10-22T22:17:49.000 permissions: owner 2: 1 partner1111a@owner, 1 partner2222a@owner, 1 partner3333a@owner active 2: 1 partner1111a@active, 1 partner2222a@active, 1 partner3333a@active memory: quota: 4.296 KiB used: 3.455 KiB

net bandwidth: staked: 2.0000 EOS (total stake delegated from account to self) delegated: 0.0000 EOS (total staked delegated to account from others) used: 483 bytes available: 251.8 KiB limit: 252.2 KiB

cpu bandwidth: staked: 2.0000 EOS (total stake delegated from account to self) delegated: 0.0000 EOS (total staked delegated to account from others) used: 1.193 ms available: 91.45 ms limit: 92.65 ms

EOS balances: liquid: 100.0000 EOS staked: 4.0000 EOS unstaking: 0.0000 EOS total: 104.0000 EOS

producers:

--------TARGET ACCOUNT -------------

cleos -u https://jungle2.cryptolions.io get account partner1111a created: 2019-10-22T22:15:36.000 permissions: owner 1: 1 EOS5c6B63vL2tiqKPe7qpRH5y1AmxL1r9xgEKbCujmGNdF1hztbut active 1: 1 EOS6GX1HKgmhbRgAiT3Y5qFCzj12b6SyRKje5sXANjgmkjvVS5b7H memory: quota: 4.296 KiB used: 3.543 KiB

net bandwidth: delegated: 2.0000 EOS (total staked delegated to account from others) used: 2.186 KiB available: 250 KiB limit: 252.2 KiB

cpu bandwidth: delegated: 2.0000 EOS (total staked delegated to account from others) used: 2.194 ms available: 90.45 ms limit: 92.65 ms

EOS balances: liquid: 100.0000 EOS staked: 0.0000 EOS unstaking: 0.0000 EOS total: 100.0000 EOS

TRANSACTION CODE AND OUTPUT

-------------propose trans---------------

cleos -u https://jungle2.cryptolions.io multisig propose beermoney5 '[{"actor": "partner2222a", "permission": "active"},{"actor": "partner3333a", "permission": "active"}]' '[{"actor": "mymultisig1a", "permission": "active"}]' eosio.token transfer '{"from":"mymultisig1a", "to":"partner1111a", "quantity":"2.00 EOS", "memo":"Give partner1111a some beer money"}' partner1111a

---return---

executed transaction: abc097a2ef74e0879db7aaa8ebef71c620f6561e118b2115cc5506c681f56494 264 bytes 207 us

eosio.msig <= eosio.msig::propose {"proposer":"partner1111a","proposal_name":"beermoney5","requested":[{"actor":"partner2222a","permis...
warning: transaction executed locally, but may not be confirmed by the network yet

------------review trans-----------------

cleos -u https://jungle2.cryptolions.io multisig review partner1111a beermoney5

-----output-----

{ "proposer": "partner1111a", "proposal_name": "beermoney5", "transaction_id": "ccf5c899d1f0d01cdcc412d1e3bcac35e3472f039741212e498f9a66e8b53ea3", "packed_transaction": "5c08b15d000000000000000000000100a6823403ea3055000000572d3ccdcd01600273d8e5a8a59700000000a8ed323242600273d8e5a8a597604208e1aa99afa9c80000000000000002454f5300000000214769766520706172746e6572313131316120736f6d652062656572206d6f6e657900", "transaction": { "expiration": "2019-10-24T02:11:40", "ref_block_num": 0, "ref_block_prefix": 0, "max_net_usage_words": 0, "max_cpu_usage_ms": 0, "delay_sec": 0, "context_free_actions": [], "actions": [{ "account": "eosio.token", "name": "transfer", "authorization": [{ "actor": "mymultisig1a", "permission": "active" } ], "data": { "from": "mymultisig1a", "to": "partner1111a", "quantity": "2.00 EOS", "memo": "Give partner1111a some beer money" }, "hex_data": "600273d8e5a8a597604208e1aa99afa9c80000000000000002454f5300000000214769766520706172746e6572313131316120736f6d652062656572206d6f6e6579" } ], "transaction_extensions": [] } }

------------partner2222a approve trans----

cleos -u https://jungle2.cryptolions.io multisig approve partner1111a beermoney5 '{"actor": "partner2222a", "permission": "active"}' -p partner2222a@active

---output-----

executed transaction: 06e74d30ddd2ed56d7f13d8732dbdd1b2eaf9e8e475a87fb5901d5cdee58d1ef 128 bytes 215 us

eosio.msig <= eosio.msig::approve {"proposer":"partner1111a","proposal_name":"beermoney5","level":{"actor":"partner2222a","permission"...
warning: transaction executed locally, but may not be confirmed by the network yet

----------partner3333a approve trans----

cleos -u https://jungle2.cryptolions.io multisig approve partner1111a beermoney5 '{"actor": "partner3333a", "permission": "active"}' -p partner3333a@active

----output------

executed transaction: 5251070a512ee51bfe60e9dba7e27135d168f48d950e05ddf532ddb0b413c80d 128 bytes 205 us

eosio.msig <= eosio.msig::approve {"proposer":"partner1111a","proposal_name":"beermoney5","level":{"actor":"partner3333a","permission"...
warning: transaction executed locally, but may not be confirmed by the network yet ]

---------exec trans--------------------

cleos -u https://jungle2.cryptolions.io multisig exec partner1111a beermoney5 -p partner1111a@active

---------exec trans-------------------- executed transaction: d669c434378689680ce3bc63883f28a7786387fdf9f2533a1246d6b95489b07a 160 bytes 317 us

eosio.msig <= eosio.msig::exec {"proposer":"partner1111a","proposal_name":"beermoney5","executer":"partner1111a"}
warning: transaction executed locally, but may not be confirmed by the network yet ] -------------done----------------------

POST TRANSACTION BALANCES

----------SOURCE MSIG ACCOUNT ---------------

cleos -u https://jungle2.cryptolions.io get account mymultisig1a created: 2019-10-22T22:17:49.000 permissions: owner 2: 1 partner1111a@owner, 1 partner2222a@owner, 1 partner3333a@owner active 2: 1 partner1111a@active, 1 partner2222a@active, 1 partner3333a@active memory: quota: 4.296 KiB used: 3.455 KiB

net bandwidth: staked: 2.0000 EOS (total stake delegated from account to self) delegated: 0.0000 EOS (total staked delegated to account from others) used: 475 bytes available: 251.8 KiB limit: 252.2 KiB

cpu bandwidth: staked: 2.0000 EOS (total stake delegated from account to self) delegated: 0.0000 EOS (total staked delegated to account from others) used: 1.383 ms available: 91.26 ms limit: 92.65 ms

EOS balances: liquid: 100.0000 EOS staked: 4.0000 EOS unstaking: 0.0000 EOS total: 104.0000 EOS

producers:

---------- DESTINATION ACCOUNT --------------

cleos -u https://jungle2.cryptolions.io get account partner1111a created: 2019-10-22T22:15:36.000 permissions: owner 1: 1 EOS5c6B63vL2tiqKPe7qpRH5y1AmxL1r9xgEKbCujmGNdF1hztbut active 1: 1 EOS6GX1HKgmhbRgAiT3Y5qFCzj12b6SyRKje5sXANjgmkjvVS5b7H memory: quota: 4.296 KiB used: 3.543 KiB

net bandwidth: delegated: 2.0000 EOS (total staked delegated to account from others) used: 2.564 KiB available: 249.7 KiB limit: 252.2 KiB

cpu bandwidth: delegated: 2.0000 EOS (total staked delegated to account from others) used: 2.647 ms available: 90 ms limit: 92.65 ms

EOS balances: liquid: 100.0000 EOS staked: 0.0000 EOS unstaking: 0.0000 EOS total: 100.0000 EOS

------explorer output -------------

explorer output for the exec action

Is this a bug? Seems like this should be impossible without raising an error.

I know that's alot, but I'm stumped. Any help would be much appreciated.

Thanks

**Comment by b1bart** [comment]
This is a nuance of all deferred transactions which is what `eosio.msig` uses to execute transactions.   You can see the retirement of the `eosio.msig::exec` as transasction ID:[`d669c434...`](https://jungle.eosq.app/tx/d669c434378689680ce3bc63883f28a7786387fdf9f2533a1246d6b95489b07a)

This created a deferred transaction with the ID [`1e1ea2f9ea0b05ff28cb9cafbfec12933ada2447a779c7cb2652165ac05a23e5`](https://jungle.eosq.app/tx/1e1ea2f9ea0b05ff28cb9cafbfec12933ada2447a779c7cb2652165ac05a23e5) which retired in block [56,187,242](https://jungle.eosq.app/block/0359596ac2dbfd9094abec7efac8111ea737f1ca3f8c7d11559859a44c3e06e1) . The most important thing to note about this transaction's retirement in that block is the **state field** which indicates that it is a "Soft Failure" with an associated message: "symbol precision mismatch".

This means that the blockchain attempted to execute the deferred transaction and determined that it was objectively always going to fail.  The "soft" part, indicates that the blockchain successfully ran the `onerror` method of the contract (which in this case did nothing).   We have that handler as a last resort for the contract to attempt to recover but regardless of its success or failure, the primary transaction (your deferred transaction) was considered failed and **no side effects will be present on the chain as a result**.

For your specific error, it seems that you only specified 2 decimal places of precision on your transfer and that token requires exactly 4.

you can read more about the state of a transaction on our [Developer Portal](https://developers.eos.io/eosio-nodeos/docs/how-to-monitor-state#section-transaction-states)
