### ISSUE TITLE
generate asset amount as string 

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.contracts#39]
Need a function that generates a string representation of an asset.

Something along these lines will be great to have in asset.hpp:
https://medium.com/@cc32d9/printing-asset-amount-in-eosio-assert-99122107bfdd

**Comment by cc32d9** [comment]
oops, eosiolib is not in this repo. Should I recreate it in eos repo?

**Comment by deckb** [comment]
We are doing some clean up and are closing old issues. Please reopen in the [new token repo](https://github.com/EOSIO/eosio.token).
