### ISSUE TITLE
Source annotations should be Standardese compatible 

### ISSUE THREAD

**Issue by dskvr** [EOSIO/eosio.contracts#392]
Currently source annotations are using `javadoc` style comments that are compatible with Doxygen. However, the coding style used in EOSIO contracts have evolved and are no longer Doxygen-compatible. This is why we're employing `mdjavadoc` as a stop-gap to parse _only the actions_ in the documentation after some preprocessing; namely removal of `[[eosio declarations]]`. 

Standardese appears to be the best option for documenting C++ projects that have modified LLVM and/or implement advanced coding styles at this point in time, and EOSIO meets both these criteria. 

Testing Standardese with EOSIO LLVM has been conducted on the `EOSIO/history-tools` repo with success. 

To extend this effort to `eosio.contracts` the following steps must first be completed: 

1. Convert `javadoc` style comments that start with `@` to Standardese style comments that start with `\` and convert all Standardese incompatible sections to Standardese compatible sections, and expand lengthy doc strings. 

> The current sections are all the C++ standard lists in [structure.specifications]/3 like \effects, \requires, \returns and \throws, details [here](http://eel.is/c++draft/structure.specifications#3)

2. Build standardese with EOSIO's LLVM (See example [here](https://github.com/EOSIO/history-tools/blob/master/build-docs-base.dockerfile#L54-L62))

[See Standardese Docs for Markup Reference](https://github.com/standardese/standardese)

Test output, and submit PR for review. Please resolve this issue in submitted PR.

**Comment by deckb** [comment]
It appears that the standardese development has be stopped so going to close this issue for now.
