### ISSUE TITLE
enum in [[eosio::table]] leads to "Error 3015004: The type defined in the ABI is invalid"

### ISSUE THREAD

**Issue by godmar** [EOSIO/eosio.contracts#394]
My apologies if this is documented somewhere.

When I try to define:
```
enum EnumType : uint8_t { VALUE0, VALUE1, VALUE2 };
struct [[eosio::table]] T
{
  EnumType state;
}
```
I get when running `cleos get table ... `
```
Error 3015004: The type defined in the ABI is invalid
Error Details:
state
```
It's not clear if the fix is to define this type somehow in the ABI or whether `enum` cannot be used. Please document.

**Comment by sanaraufx** [comment]
Cleaning up old issues so we can focus on more recent open items. Please reopen this ticket if needed. Thank you.
