### ISSUE TITLE
eosio.contracts 1.9.0 producer scheduling problem

### ISSUE THREAD

**Issue by enumivo-core** [EOSIO/eosio.contracts#435]
eosio 1.9.0

when running cleos system unregprod, it sets producer key to EOS1111111111111111111111111111111114T1Anm and it still has some votes. those voting the producer does not remove in its list of voted producers. and the producer still produces blocks.

**Comment by enumivo-core** [comment]
we started a chain with eosio.contracts 1.8.3, tried voting and changing the votes and the producer schedule changes as well without any problem, then we upgrade to 1.9.0, and no matter how we change the voting, the active schedule remains fixed. any workaround?

**Comment by enumivo-core** [comment]
reverting it to 1.8.3 fixes the producer scheduling. it's definitely an eosio.contracts 1.9.0 problem.

**Comment by arhag** [comment]
@enumivo-core:

There indeed is a bug in eosio.contracts v1.9.0 that causes problems during `onblock` (which is responsible for producer schedule changes, producer pay, and a few other things) when transitioning from the producer tables generated in prior versions.

A simple workaround is for all of the top active producers to call the `regproducer` (or `regproducer2`) action to correct their produce table record and the system should resolve itself.

I also have a fix in the system contract that should prevent the problem from occurring in the first place (when upgrading from system contract versions prior to v1.9.0 while skipping over v1.9.0) and which is able to resolve the `onblock` failures immediately (if v1.9.0 was already deployed on a chain) even without requiring the producers to take any action. If you would like to try it out early on a test network, it is available in [`435-producer-scheduling-1.9` branch](https://github.com/EOSIO/eosio.contracts/tree/435-producer-scheduling-1.9).

**Comment by enumivo-core** [comment]
call regproducer fixed our testnet, thanks @arhag

**Comment by arhag** [comment]
This issue was resolved by #445 (and #446 for v1.9.x). The fix was released in [eosio.contracts v1.9.1](https://github.com/EOSIO/eosio.contracts/releases/tag/v1.9.1).
