### ISSUE TITLE
[docs] Table is rendering or correct format?

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.contracts#451]
The action table for token contract is not rendering:

https://developers.eos.io/manuals/eosio.contracts/latest/index/#eosiotoken-system-contract

File: [docs/index.md](https://github.com/EOSIO/eosio.contracts/blob/develop/docs/index.md)

**Comment by dixia** [comment]
What is the update on this? it is in who's hand right now? @duncand0nuts

**Comment by iamveritas** [comment]
this is fixed in `1.9.x` and in `1.8.x` (see above the merged PRs)
als fixed in `develop` branch by this #391
