### ISSUE TITLE
[docs] incorrect description in "RAM as resource" page

### ISSUE THREAD

**Issue by bezalel** [EOSIO/eosio.contracts#481]
File: [docs/01_key-concepts/02_ram.md](https://github.com/EOSIO/eosio.contracts/blob/develop/docs/01_key-concepts/02_ram.md)

the block producers decided to increase the memory with 1KiB (1024 bytes) per day
=> the block producers decided to increase the memory with 1KiB (1024 bytes) per block

**Comment by iamveritas** [comment]
PR is blocked by known build issues with release/1.9.x branch

**Comment by iamveritas** [comment]
@bezalel thank you for your contribution.
