### ISSUE TITLE
How to encrypt and decrypt text in smart contract ?

### ISSUE THREAD

**Issue by gzliudan** [EOSIO/eosio.contracts#484]
I'm writing a chat contract with C++ language. Is it possible that sender use receiver's public key to encrypt text, and receiver use his own private key to decrypt text? If it's OK, then how can sender get receiver's public key, and receiver get his own private key? What's encrypt and decrypt function name in eos C++ library? If eos cdt has no such function, which library is suggest for eos contract?

**Comment by heifner** [comment]
Issues are for issues in contracts, not for questions. I suggest you ask on telegram `EOSIO Developers`.
