### ISSUE TITLE
enhancement: secondary index on "receiver" for cpuloan and netloan tables

### ISSUE THREAD

**Issue by piecesnbits** [EOSIO/eosio.contracts#489]
To manage resources of an account it would be very handy to get the loans by receiver.

**Comment by piecesnbits** [comment]
I would suggest adding cpuloan2 and netloan2 tables with an extra secondary index on "receiver". when all loans in the original tables are expired they can be deprecated.

**Comment by deckb** [comment]
With the introduction of the PowerUp model REX is likely to be phased out of use.
