### ISSUE TITLE
Status on deprecating deferred transactions from EOSIO system contracts

### ISSUE THREAD

**Issue by DenisCarriere** [EOSIO/eosio.contracts#496]
Is there any updates on the deprecation of deferred transactions from the EOSIO system contracts, in particular the `eosio.msig` contract.

Last edits were done 3 months ago, does this mean this is complete or is still under review?

https://github.com/EOSIO/eosio.contracts/tree/develop-deprecate-deferred-trx

There are more and more deferred transactions clogging the network and soon it will be near impossible to push an MSIG on EOS Mainnet.

Example of deferred transaction flooding the network.
https://eosq.app/tx/695382002edefa0ec9352e1c4af500f3d8b404af150d096d204c72a74abe808d

![image](https://user-images.githubusercontent.com/550895/84168380-57c1b780-aa45-11ea-9e4f-c28e631e7915.png)

CC: @johndebord @arhag

**Comment by lukestokes** [comment]
> it will be near impossible to push an MSIG on EOS Mainnet.

Yep. We've worked to get our eosDAC custodians (10 of 12) to sign an msig which we tried to execute today but it timed out. Kind of hard to run a DAC using msig if coordinating signatures ends up being a waste of time. We look forward to whatever solutions exist for this.

**Comment by qiushaoxi** [comment]
yes, the bug is , run endless loop in onerror function can avoid pay the defer tx bill.
it should be fixed

**Comment by b1bart** [comment]
@DenisCarriere There will be some ABI changes necessary to respect the existence of `waits` in the authorizations.  Those ABI changes do not affect the actions issued to operate the contract AFAIK but will affect the table data for things such as approvals.  

We will seek to clearly outline these changes as part of the release notes that come with the patch.

**Comment by andrew-p-bryan** [comment]
dac.vigor.ai seeing many deferred transactions expiring, many msigs failing based on their dependence on deferred

**Comment by maximusmaximus** [comment]
Same as VIGOR, at KROWN DAC all of the msigs failing, all expiring upon execution at dac.krown.club

**Comment by CodingOnMyCouch** [comment]
There seems to be a spike in the number of failing deferred transactions. This has been experienced by myself and other members of the Vigor DAC. To prevent this inconvenience and for security reasons a fix is much needed.

**Comment by webdave2000** [comment]
More than 50% of MSIG deferred transactions are expiring at the moment. DAC organizations are one of the bright spots on EOSIO , we need help ASAP!

**Comment by JOUNGHEECHO** [comment]
[https://dac.vigor.ai]() 
seeing many deferred transactions expiring, many msigs failing based on their dependence on deferred
Today Creat msig Proposal All deferred expired!!
Need help msig on EOS Mainnet!

**Comment by eosusa** [comment]
Not being able to reliably execute msigs due to the deferred transaction expiring is impacting several of our projects we work with.  Please look to have this update deployed ASAP to resolve the issues and get msigs working reliably again on all EOSIO chains.

**Comment by eoswatchdogs** [comment]
Please patch this asap. this is a long standing issue that is affecting the growth of the ecosystem. Please put more focused attention towards this.

**Comment by dali1986** [comment]
This has now become a major issue for DACs on EOS and affects some important functionality of the chain. On eosDAC, the custodians have been unable to make approved payments. This is potentially causing liability risks and forcing processes to be changed ad-hoc. Also, as it stands, the forthcoming DACFactory will not be able to function until this issue is resolved. Please patch asap.

**Comment by EOS-CSX** [comment]
All of the msigs are failing for KROWN DAC.  
All expiring upon execution at dac.krown.club

**Comment by matthewdarwin** [comment]
From EOS Mainnet BPs telegram:

![image](https://user-images.githubusercontent.com/26171839/85298144-b89fb580-b471-11ea-9805-8ba7c2f1ba89.png)

**Comment by FortisFortuna** [comment]
We are having msig issues too now. They were working before

**Comment by qiushaoxi** [comment]
> We are having msig issues too now. They were working before

you can sign transaction offchain now, temporarily

**Comment by cf** [comment]
Please fix this ASAP, has interfered with some of our upcoming projects

**Comment by dallasjohnson** [comment]
I'm also having issues with this. I'm in the process of refactoring contracts around using unreliable deferred transactions and having a deferred transaction stuck there in the `eosio.msig` is a very awkward bottleneck. 

This is very high priority for anyone using the supposed high security of msigs on eosio but if they don't work then it's pretty useless.
 
At the moment there are several DAC's using this software and are fairly well blocked from operation due to this issue.

 More frequent updates on this would give us some confidence that this issue is actually being addressed as a high priority.
