### ISSUE TITLE
Block producer greylisting

### ISSUE THREAD

**Issue by jjssoftware** [EOSIO/eosio.contracts#50]
Would it be possible to implement a feature to greylist / deactivate a block producer when they fail to produce blocks? 

If it's detected that a top 21 block producer stops producing blocks, that BP could be flagged as inactive and removed from the top 21 until the situation is remedied.

This is one of the ideas originally tabled in https://github.com/EOSIO/eos/issues/5311

**Comment by gleehokie** [comment]
@jjssoftware it is possible for the BPs to do this currently using an msig proposal.  In the near future it will be even easier using the sudo/wrap contract assuming the contract is adopted.

**Comment by jjssoftware** [comment]
With respect @gleehokie this issue has been closed with an assumption that it's fine for BPs to have to step in and agree that there is an issue when an issue is identified with a BP failing to produce blocks in order for that failing BP to be removed.

Your closing comment ignores the idea that greylisting of broken BPs could be automated and system managed to prevent undesirable delays and platform performance degradation for extended periods of time. This is not a theoretical concern, undesirable platform performance degradation issues have been seen in the past when a top 21 BP has failed.

LiquidEOS (eosliquideos) have attempted to address and close this gap with their [eos-bp-watchdog](https://github.com/bancorprotocol/eos-bp-watchdog) script but BPs can choose to not introduce and use this script for many reasons.

If the EOSIO accepted way is for human intervention to be required in cases that realistically could be system managed that's fine but if so, the community needs to be aware that there is a risk of platform performance degradation issues being seen again if / when a BP fails in the future.

**Comment by gleehokie** [comment]
Reopening for further consideration

**Comment by deckb** [comment]
Doing some housekeeping and closing old tickets. If desired please reopen in the [new system repository](https://github.com/eosio/eosio.system).
