### ISSUE TITLE
Enhancement: parabolic resource costs

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.contracts#507]
In current system contract, the account CPU and NET weight is linearly proportional to the stake of system token. This makes spamming relatively cheap, and leads to congestion on EOS mainnet.

In this proposal, the weight would be proportional to square root of stake amount. This would not make much difference for occasionally transacting accounts, but frequent senders will have to stake a lot more. This should reduce the spamming.

The `eosio.system` contract is calling the `set_resource_limits()` intrinsic in several places. Instead, it would call a member function that would calculate the weight according to a new formula:

```
weight = alpha + beta * sqrt(gamma * stake);
```
alpha, beta, gamma should be configurable parameters and separate for NET and CPU.

Also there should be a transition contract that goes through all accounts and adjusts their current weight in batches.

**Comment by tbfleming** [comment]
How could we protect this against splitting stake across multiple accounts?

**Comment by cc32d9** [comment]
cost factor of creating and orchestrating thousands of accounts would be prohibitive. We can't ban the junk traffic, but we can make it expensive. Then either the system token price goes up because of demand, or junk stops because it becomes unprofitable.

It needs thorough modeling. Probably the curve needs to be more complex.

**Comment by cc32d9** [comment]
another possible option is to count the contract's execution frequency, not the user's. So, noisy contracts would be more expensive to access (probably eosio.token will need an exception)

**Comment by deckb** [comment]
Does the transition to the PowerUp model alleviate the so-called spam issue this was attempting to solve?

**Comment by cc32d9** [comment]
it seems like Powerup solved the issue in a better way.
