### ISSUE TITLE
Notification to proxies when their voters change vote

### ISSUE THREAD

**Issue by conr2d** [EOSIO/eosio.contracts#508]
Can you elaborate the rationale of #173?

Nowadays, it's inevitable that many proxy accounts distribute their earnings to their voters. However, changing vote cannot be caught by notification, so observing and updating state cannot be achieved on-chain, but it needs off-chain solution.

It would be better, if changing vote is notified to a proxy (when the target itself of vote is not changed, but vote weight changes, `eosio::delegatebw` or `eosio::undelegatebw`) or both old and new proxies (when they are different, `eosio::voteproducer`).

**Comment by tbfleming** [comment]
Notification allows the proxy to assert, aborting the transaction and preventing the voter from making the change.

**Comment by conr2d** [comment]
@tbfleming Ah, I missed that. Thank you for replying.
