### ISSUE TITLE
how to parse the transaction detail information from inline actions?

### ISSUE THREAD

**Issue by harryweiyongjie** [EOSIO/eosio.contracts#516]
just like this tx, https://www.eosx.io/tx/515981cbee0f48c1e07a5464c37681176c02160c92eb9ea4094117f49b2b2236?listView=raw

**Comment by harryweiyongjie** [comment]
this is a tx which is created by smart contract, but how can I parse the 'from' 'to' 'coin' 'amount' in the raw data?

**Comment by deckb** [comment]
You can use the eosjs library and either [deserializeActionData](https://github.com/EOSIO/eosjs/blob/1cf9bf53d21d3f461f61970d3295ee1fc2ba56d1/src/eosjs-serialize.ts#L1134) or the [deserializeAction](https://github.com/EOSIO/eosjs/blob/1cf9bf53d21d3f461f61970d3295ee1fc2ba56d1/src/eosjs-serialize.ts#L1151) functions.

**Comment by harryweiyongjie** [comment]
> You can use the eosjs library and either [deserializeActionData](https://github.com/EOSIO/eosjs/blob/1cf9bf53d21d3f461f61970d3295ee1fc2ba56d1/src/eosjs-serialize.ts#L1134) or the [deserializeAction](https://github.com/EOSIO/eosjs/blob/1cf9bf53d21d3f461f61970d3295ee1fc2ba56d1/src/eosjs-serialize.ts#L1151) functions.

ok,thanks,I'll try.
