### ISSUE TITLE
eosio.msig can undo account transfers.

### ISSUE THREAD

**Issue by StarryJapanNight** [EOSIO/eosio.contracts#53]
**Problem**

There are currently two competing EOS account exchanges live:
[https://www.eosnameswaps.com](url)
[https://eoscontract.io/exchangename](url)

As documented here,[https://medium.com/@motchamotcha/eosio-multisig-contract-vulnerability-b5289d18223f](url), both dApps are vunerable to unexecuted eosio.msig proposal/approvals that restore an accounts permission after it has been transferred to a new user.

It is currently possible to check the eosio.msig tables for proposal/approvals by the account in question. It is not possible to check whether a proposal that affects the permission of an account has been proposed by a different account. There is therefore no guaranteed in-contract method for transferring accounts. Other applications, such as account lending and ram shorting, can also not be developed.

**Possible Solution**

Modify eosio.msig to emplace the account name that is being affected by an msig action into a table that can be searched.

Note: There is similar vunerability with deferred transactions.

**Comment by StarryJapanNight** [comment]
A simpler solution may be to enforce a rule that msig updateauth transactions can only be proposed by the account being affected by the permission change.

**Comment by StarryJapanNight** [comment]
Or perhaps an unapproveall action. There is currently no way to know what msig transactions are approved, but not executed, by an account. The assumption is the account owner approved these; that may or may not be the case.

**Comment by moskvanaft** [comment]
@StarryJapanNight ,
from https://medium.com/@motchamotcha/eosio-multisig-contract-vulnerability-b5289d18223f
>  However, if user2 now executes the multisig proposal,
Is there any way to trick user2 into executing the proposal?
If no, I would say that there is no vulnerability here, since people normally don't execute random multisig proposals without reviewing them.
Right now I am not saying that there is nothing to improve here. Just want to make sure that my understanding of severity of this issue is correct.

**Comment by moskvanaft** [comment]
>  There is similar vunerability with deferred transactions.

What do you mean?

**Comment by StarryJapanNight** [comment]
User2 and user1 are both controlled by the same individual. By using the user2 account to execute the msig proposal, it will not be listed under user1's scope. Once the user1 account is transfered to a new owner (say user3), there is no way they would know about the proposals made by user2. Yet they have the ability to change user1's permissions at any time.

Deferred actions can be used to set a permissions change that doesn't execute for months later. Again, only by searching blocks can a new owner know this exists. 

There needs to be in-contract methods for detecting live msig/deferred transactions.

**Comment by StarryJapanNight** [comment]
Can we make a decision on whether this needs attention or not?

**Comment by moskvanaft** [comment]
Although selling accounts was not a feature that we originally intended to support, we are planing a fix in multisig contract for this issue.

**Comment by moskvanaft** [comment]
@StarryJapanNight 
Now multisig contract supports action "invalidate" which invalidates all previous approvals. So, you will need to call it when you transfer ownership of an account (calling it it in the same transaction is the safest).
The fix is available in `develop` branch. So, it should be included in the next release. Than it will be up to block producers to upgrade multisig contract on mainnet.

**Comment by StarryJapanNight** [comment]
Excellent work. This is simple for me to implement. Two questions:

* Will this invalidate all historical msig proposals related to an account? Even before the code change?

* Is it possible to make a similar change for deferred actions?

**Comment by StarryJapanNight** [comment]
Thank you for your detailed response. My current solution is once the account ownership has been transferred to the contract, to manually screen it for possible complications before allowing it to be sold. This is effectively the escrow you talk about. While this solution is most definitely not decentralized, nor programmatic, I believe it can resolve most of the potential issues with minimal burden to the developer.  Other developers may not like this solution, but for the specific case of account exchanges, I don't currently see any alternative.

I appreciate the efforts that have gone into thinking about this problem. The msig code update potentially helps resolve issues for other types of contracts, and is a valued addition in itself.
