### ISSUE TITLE
Tiny typo correction[docs] Suggestion / Change Request

### ISSUE THREAD

**Issue by goodengineer** [EOSIO/eosio.contracts#546]
Code: [Source](https://github.com/EOSIO/eosio.contracts/blob/develop/)

Parameter Name | Description
-- | --
payer | - the ram buyer,
receiver | - the ram receiver,
quant | - the quantity(here I spotted and added corrective "a") of tokens to buy ram with.

Parameter Name | Description
-- | --
payer | - the ram buyer,
receiver | - the ram receiver,
bytes | - the quantity(here I spotted and added corrective "a") of ram to buy specified in bytes.

updtrevision
Type: void

Update revision action, updates the current revision that is greater or equal 1 (“set upper bound to greatest revision supported in the code”).
Parameter Name | Description
-- | --
revision | - it has to be incremented by 1 compared with current revision.

**Comment by deckb** [comment]
This should be fixed now.
