### ISSUE TITLE
Tiny typo correction in a table[docs] Suggestion / Change Request

### ISSUE THREAD

**Issue by goodengineer** [EOSIO/eosio.contracts#549]
In next table parameter quantity:

Parameter Name | Description
-- | --
to | - the account to issue tokens to, it must be the same as the issuer,
quantity | - the amount of tokens to be issued,

  Code: [Source](https://github.com/EOSIO/eosio.contracts/blob/develop/)

**Comment by deckb** [comment]
I believe this has been fixed in the develop branch.
