### ISSUE TITLE
[docs] Suggestion / Invalid parameter name in the issue action.

### ISSUE THREAD

**Issue by meetmorrowsolonmars** [EOSIO/eosio.contracts#559]
The **quantity** parameter in the parameter description table is misspelled **quntity**.
[eosio.token::issue](https://developers.eos.io/manuals/eosio.contracts/latest/action-reference/eosio.token/index/#issue)
![image](https://user-images.githubusercontent.com/24230649/111260337-3389ab80-8653-11eb-8d31-9505dc4b36d1.png)

  Code: [Source](https://github.com/EOSIO/eosio.contracts/blob/develop/)

**Comment by deckb** [comment]
Thanks for pointing this out. I believe this is fixed in develop and will be propagated to the documentation site on the next release.
