### ISSUE TITLE
Error 3070003: Serialization Error Processing WASM

### ISSUE THREAD

**Issue by bigbadboii1025** [EOSIO/eosio.contracts#583]
set contract: cleos set contract eosio ./eosio.system -p eosio@active 
I get : Error 3070003: Serialization Error Processing WASM

> Publishing contract...
> Error 3070003: Serialization Error Processing WASM
> Error Details:
> env.set_proposed_producers_ex unresolveable
> pending console output:

**Comment by deckb** [comment]
The system contract you built and tried to deploy has a feature that has not been activated on the chain. Try calling https://developers.eos.io/welcome/v2.2/tutorials/bios-boot-sequence/#1121-activate-the-preactivate_feature-protocol and deploying again.
