### ISSUE TITLE
Fix EOSIO dependency version

### ISSUE THREAD

**Issue by xJonathanLEI** [EOSIO/eosio.contracts#64]
The latest version of `eos` is `v1.2.3`. With this version installed, the `build.sh` script throws an error:

    CMake Error at CMakeLists.txt:9 (message):
      Incorrect EOSIO version, please use version 1.1.x

There's no point in depending on an old version. Please fix it.

**Comment by arhag** [comment]
See https://github.com/EOSIO/eosio.contracts/pull/65#issuecomment-417878531.

I'm leaving this issue open for now until the v1.3.0 release is out with the fix.
