### ISSUE TITLE
Is it possible to implement this in a smart contract ?

### ISSUE THREAD

**Issue by otac0074** [EOSIO/eosio.contracts#73]
There are A, B, C, and D cards.
I would like to distribute this card at random without knowing each other.

User1: A
User2: B
User3: C
User4: D

The user should not know what his / her other card is
Duplication is not possible.

Is it possible?

**Comment by arhag** [comment]
It is possible to do with cryptography, but not easy. I recommend looking up "mental poker". 

Keep in mind that every piece of data accessible to a contract deployed on a public blockchain is viewable to anyone in the world. The only way to hide information is to properly use cryptographically, which is often not an easy task.

By the way, the GitHub issues of this repository are not the appropriate place to ask these types of questions. I recommend trying something like eosio.stackexchange.com or Telegram groups dedicated towards EOS contract development.
