### ISSUE TITLE
Proxy vote decay

### ISSUE THREAD

**Issue by gammastrat** [EOSIO/eosio.contracts#77]
Vote decay is important for the health of the EOS ecosystem. It's also important to have engagement from the community through the proxy option. Unfortunately, the way the code is today a user must re-up their vote to the proxy in order to remain at full voting strength. This defeats the purpose of having a proxy. 

Example:

If Bob delegates his token votes to Alice, then Bob is giving Alice the authority to make decisions on Bob's behalf. 
If Alice wants to re-up the vote to full strength at the end of the week, Alice shouldn't have to ask Bob to re-up his vote to Alice...as Bob's consent was already given.

I see 2 options for proxies:
1. No vote decay if you proxy
2. Vote decay is had, but it's something less than the current 1 week vote decay (perhaps Bob will need to re-up his vote to Alice once every 6 months or else decay begins on 6 months and 1 day).

Looking for feedback on this proposal and what it might take to implement this in a future release.

**Comment by aaroncox** [comment]
Anecdotal evidence, but based on my interactions with the community - both voters and proxies dislike the fact that proxied weight decays. 

A common use case for a large stakeholder is to use an offline/cold storage account for the majority of their funds and then proxy voting rights to a smaller hot wallet. The hot wallet can securely recast those votes (while experiencing decay), but it's inconvenient for them to have to continually re-use the cold wallet to reset the proxy, thus resetting the decay. If decay didn't exist on the proxy, the stakeholder could then just manage their voting from the lesser hot wallet, without having to touch the cold wallet.

**Comment by craigmurray100** [comment]
I think it makes sense to require people to re-vote for the proxy they like.  Force them to engage.  They can set up a permission so they can use a key that only has the power to voteproducer and nothing else, then it's safe to use on a hot wallet and not worry about losing funds.

**Comment by eny-rs** [comment]
@craigmurray100 also please see the second example where vote decay is still had, but at a reduced rate. So in that example the person would still need to re-vote, just not as often as once a week to maximize vote strength. 

Further, my perspective is that someone that proxies is giving their decision making power they feel is more informed or has the ability to stay up to date better than the delegator. Think about republics where representatives are used in place of pure democracy; same principle.

**Comment by Boid-John** [comment]
https://medium.com/@eos42/cooperative-voting-infrastructure-bounties-19c6f39cf57d

**Comment by deckb** [comment]
We are doing some housekeeping and closing old issues. If desired please reopen this issue in the [new system contract repo](https://github.com/EOSIO/eosio.system)
