### ISSUE TITLE
Some structures of eosio.sytem are outdated

### ISSUE THREAD

**Issue by zxcat** [EOSIO/eosio.contracts#86]
`authority` structure cannot be used, de-serializetion fails.
eosio.system defines it as:
https://github.com/EOSIO/eosio.contracts/blob/7658e594239158a2e4106628aedd0caa6e2cba02/eosio.system/include/eosio.system/native.hpp#L38-L42

but eos changed definition to:
https://github.com/EOSIO/eos/blob/905e7c85714aee4286fa180ce946f15ceb4ce73c/libraries/chain/include/eosio/chain/authority.hpp#L73-L76

There are some other outdated structures, as mentioned in EOSIO/eos#4684 and linked issues

**Comment by arhag** [comment]
Resolved by #90.
