### ISSUE TITLE
eosio.msig approve is subject to TOCTOU race condition

### ISSUE THREAD

**Issue by fproulx-eoscanada** [EOSIO/eosio.contracts#87]
When user approves a multisig proposal there is no hard guarantee that he is approving exactly what he has reviewed. 

For instance, someone takes multiple days to review a complex proposal that is changing a smart contract or whatever and approves without double checking that the proposal has not been withdrawn and resubmitted under the same exact name between the review and the approval.

In order to be backward compat, there should be a new approve action with a proposal hash.

**Comment by gleehokie** [comment]
Or identify the transaction # containing the proposal that you are approving.

**Comment by fproulx-eoscanada** [comment]
Yeah specifying the transaction ID that created the proposal would be sufficient.

**Comment by arhag** [comment]
Resolved by #121.
