### ISSUE TITLE
Voting Requirements for REX

### ISSUE THREAD

**Issue by DenisCarriere** [EOSIO/eosio.contracts#91]
# Voting Requirements

> In order to buy REX an account must set and maintain a voting proxy or approve at least 21 block producers. They may change their votes but not remove them while they hold REX tokens. After an account has sold all REX tokens they may vote for less than 21 producers.

Ref: https://medium.com/@bytemaster/proposal-for-eos-resource-renting-rent-distribution-9afe8fb3883a

I'm assuming this will be enforced in the REX smart contract? Will these asserts be located in [eosio.system/src/rex.cpp](https://github.com/EOSIO/eosio.contracts/blob/rex-2/eosio.system/src/rex.cpp) or another module?

**Comment by zorba80** [comment]
The asserts are now in rex.cpp and voting.cpp

**Comment by jjssoftware** [comment]
Please see my related comment here in the REX pull request that discusses gaming access to REX rewards via personal proxies that have a low BP count:

https://github.com/EOSIO/eosio.contracts/pull/94#issuecomment-427661271
